export default {
	contentList: [
		{
			id: '1',
			name: 'Карина',
			imgSrc: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
			datetime: '10:49',
			lastMessageText: 'Изображение',
			countNewMessage: '2',
			isCountNewMessageHidden: false,
		},
		{
			id: '2',
			name: 'Андрей',
			imgSrc: '',
			datetime: '10:49',
			lastMessageText: 'Изображение',
			countNewMessage: '10',
			isCountNewMessageHidden: true,
		},
		{
			id: '3',
			name: 'Кирилл',
			imgSrc: '',
			datetime: '10:49',
			lastMessageText: 'Изображение',
			countNewMessage: '10',
			isCountNewMessageHidden: false,
		},
		{
			id: '4',
			name: 'Киноклуб',
			imgSrc: '',
			datetime: '10:49',
			lastMessageText: 'Изображение',
			countNewMessage: '6',
			isCountNewMessageHidden: false,
		},
		{
			id: '5',
			name: 'Андрей',
			imgSrc: '',
			datetime: '10:49',
			lastMessageText: 'Изображение',
			countNewMessage: '10',
			isCountNewMessageHidden: true,
		},
	],
};
