export  default  [
    {
        label:'Почта',
        type:'email',
        value:'',
        name:'email'
    },
    {
        label:'Логин',
        type:'text',
        value:'',
        name:'login'
    },
    {
        label:'Имя',
        type:'text',
        value:'',
        name:'first_name'
    },
    {
        label:'Фамилия',
        type:'text',
        value:'',
        name:'second_name',
    },
    {
        label:'Телефон',
        type:'tel',
        value:'',
        name:'phone',
    },
    {
        label:'Пароль',
        type:'password',
        value:'',
        name:'password'
    },
    {
        label:'Пароль (еще раз)',
        type:'password',
        value:'',
        name:'password2'
    },
]